HugoByte/DIVE

- README.md
- kurtosis.yml
```bash
chore: update package yaml
```
> chore: update package yaml

- README.md
```bash
test: update readme to add link to test folder
```
> chore: Update readme with link to test folder

- README.md
```bash
chore: update test folder link in ReadMe
```
```bash
```
> chore: update test folder link in ReadMe

- cli/commands/discord/discord.go
- cli/commands/root.go
```bash
feat: implement discord command
```
> feat: Ckip 80 add discord command to dive cli

- cli/commands/discord/discord.go
- cli/commands/root.go
- cli/commands/twitter/twitter.go
- cli/common/types.go
```bash
feat: implement twitter command
```
> feat: Ckip 79 add command for twitter in dive cli

- cli/commands/bridge/bridge.go
- cli/commands/chain/types/eth.go
- cli/commands/chain/types/hardhat.go
- cli/commands/chain/types/icon.go
- cli/commands/root.go
- cli/common/types.go
- cli/main.go
- services/jvm/icon/static-files/config/start.sh
```bash
fix: bug fixes for dive cli 
```
> fix: bug fixes for dive cli 

- cli/common/constants.go
- package_io/constants.star
```bash
fix: update eth starlark package
```
```bash
```
> fix: update eth starlark package

- cli/commands/discord/discord.go
```bash
fix: update discord url
```
> fix: update discord url

- README.md
- cli/.goreleaser.yaml
```bash
fix: update goreleaser yaml and README
```
> fix: update goreleaser yaml and README

- cli/commands/clean/clean.go
- cli/common/types.go
```bash
fix: remove dive.json on clean command
```
> fix: remove dive.json on clean command

- cli/commands/discord/discord.go
- cli/common/constants.go
```bash
chore: update dive version
```
> chore: update dive version

- cli/commands/chain/types/eth.go
- cli/commands/chain/types/hardhat.go
- cli/commands/chain/types/icon.go
- cli/commands/clean/clean.go
- cli/commands/root.go
- cli/common/constants.go
- cli/common/types.go
```bash
fix: remove services json file after dive clean and update verbose flag
```
> fix: remove services json file after dive clean and update verbose flag

- cli/commands/chain/types/icon.go
- cli/common/types.go
```bash
fix: services json file formatting and fix typos in logs
```
> fix: services json file formatting and fix typos in logs

- cli/common/constants.go
- cli/common/context.go
- cli/go.mod
```bash
chore: update kurtosis sdk version
```
> chore: update kurtosis sdk version

- services/evm/eth/src/node-setup/start-eth-node.star
We just updated the eth-network-package & this package will break when it tries to fetch from latest.
```bash
fix: update package to work with latest eth network package
```
```bash
version: update package to work with latest eth-network-package
```
> fix: update code to work with latest eth-network-package

- services/evm/eth/static-files/hardhat.config.ts.tmpl
- services/evm/eth/static-files/scripts/deploy_dapp.ts
- services/evm/eth/static-files/scripts/deploy_xcall.ts
```bash
fix: update dive eth package
```
> fix: update dive eth package

- main.star
```bash
fix: fix typo in main.star file
```
> fix: fix typo in main.star file

- main.star
```bash
fix: config in starlark package
```
> fix: config in starlark package

- .github/workflows/smoke-test.yaml
```bash
test: update smoke test yaml
```
```bash
```
> test: update smoke test yaml

- .github/workflows/smoke-test.yaml
- README.md
- cli/commands/bridge/bridge.go
```bash
type: commit message
```
```bash
```
> docs: Update READ.md file, change dive.json and service.json

- services/jvm/icon/src/node-setup/setup_icon_node.star
- services/jvm/icon/static-files/config/icon_config.json
```bash
fix: wait for prep icon registration
```
```bash
version: reduce wait time for prep registration
```
> fix: wait for prep icon registration

- main.star
- services/cosmvm/archway/archway.star
- services/cosmvm/archway/src/node-setup/start_node.star
```bash
feat: update cosmos ibc package
```
> feat: update cosmos ibc package

- test/Makefile
- test/functional/dive_test.go
```bash
fix: dive bin output file for running test
```
> fix: dive bin output file for running test

- test/Makefile
- test/functional/dive_test.go
```bash
fix: fix timeout and bridge command
```
> fix: fix timeout and bridge command

- test/functional/dive_test.go
- test/functional/helper.go
```bash
test: refactor functional test script
```
> test: refactor functional test script

- cli/sample-jsons/archway.json
- cli/sample-jsons/archway1.json
- test/functional/dive_test.go
- test/functional/helper.go
```bash
test: add ibc testcases to functional script
```
> test: add ibc testcases to functional script

- test/functional/dive_test.go
- test/functional/helper.go
```bash
test: add additional testcases to functional script
```
> test: add additional testcases to functional script

- package_io/constants.star
updated the relay binary architecture 
```bash
fix:update ibc relay version
```
> fix: update ibc relay version

- cli/go.mod
- test/scripts/cosmos/contracts.json
- test/scripts/cosmos/helper.ts
- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement send message from dapp archway to icon
```
> test: implement send message from dapp archway to icon

- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement verify callmessagesent event in testing script for cosmos
```
> test: implement verify callmessagesent event in testing script for cosmos

- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement check call message event
```
> test: implement check call message event

- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement execute call method
```
> test: implement execute call method

- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement call executed event
```
> test: implement call executed event

- cli/commands/bridge/relyas/common.go
- cli/commands/bridge/relyas/ibc.go
```bash
fix: error handling on invalid chain for ibc 
```
> fix: error handling on invalid chain for ibc 

- test/functional/dive_test.go
- test/scripts/cosmos/helper.ts
- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement response message event
```
> test: implement response message event

- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement rollback message event
```
> test: implement rollback message event

- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: implement rollback executed event
```
> test: implement rollbcak executed event

- test/scripts/cosmos/contracts.json
- test/scripts/cosmos/helper.ts
- test/scripts/cosmos/icon.ts
- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: icon demo script to support ibc
```
> test: icon demo script to support ibc

- test/scripts/cosmos/archway.ts
- test/scripts/cosmos/helper.ts
- test/scripts/cosmos/icon.ts
- test/scripts/cosmos/icon_archway_e2e_demo.ts
```bash
test: verify if received message received is correct
```
> test: verify if received message received is correct

- test/package.json
Add cosmos dependency in test package 
```bash
fix: dependency issue in archway-archway test script
```
```bash
```
> fix: dependency issue in archway-archway test script

- services/jvm/icon/src/node-setup/setup_icon_node.star
```bash
fix: dive starlark package run issue with Kurtosis latest version
```
```bash
version: remove unused starlark function detentions from dive package 
```
> fix: dive starlark package run issue with Kurtosis latest version

- cli/common/constants.go
- cli/go.mod
```bash
chore: bump kurtosis to 0.83.4 and dive cli to 0.0.10-beta
```
> chore: bump kurtosis to 0.83.4 and dive cli to 0.0.10-beta

- .github/workflows/archway-chain-test.yaml
- .github/workflows/bridge-test.yaml
- .github/workflows/eth-chain-test .yaml
- .github/workflows/hardhat-chain-test.yaml
- .github/workflows/icon-chain-test.yaml
- .github/workflows/misc-cmd-test.yaml
```bash
test: refactor workflow names respectively
```
> test: refactor workflow names respectively

- cli/go.mod
```bash
feat: bump cli and kurtosis version
```
```bash
```
> feat: bump cli and kurtosis version

- cli/commands/bridge/relays/btp.go
- cli/commands/bridge/relays/ibc.go
- cli/commands/chain/types/archway.go
- cli/commands/chain/types/eth.go
- cli/commands/chain/types/hardhat.go
- cli/commands/chain/types/icon.go
- cli/commands/chain/types/neutron.go
- cli/common/constants.go
- cli/common/context.go
- cli/go.mod
- package_io/constants.star
- services/jvm/icon/icon.star
```bash
fix: breaking change kurtosis update
```
```bash
version: Update Kurtosis SDK to V0.84.0
```
> fix: breaking change kurtosis update

- package_io/constants.star
- services/bridges/btp/src/bridge.star
- services/jvm/icon/icon.star
- test/Makefile
```bash
fix: file upload via relative path
```
```bash
version: Kurtosis SDK Version Bump to 0.84.0
```
> fix: file upload via relative path

- cli/commands/chain/types/archway.go
- cli/commands/chain/types/neutron.go
- cli/sample-jsons/archway.json
- cli/sample-jsons/archway1.json
- cli/sample-jsons/neutron.json
- cli/sample-jsons/neutron1.json
- services.json
- services/cosmvm/archway/archway.star
- services/cosmvm/archway/src/node-setup/start_node.star
- services/cosmvm/cosmvm.star
- services/cosmvm/neutron/neutron.star
- services/cosmvm/neutron/src/node-setup/deploy.star
- services/cosmvm/neutron/src/node-setup/start_node.star
- services/cosmvm/neutron/src/relay-setup/contract-configuration.star
… neutron and archway
This commit change the argument passing mechanism in both the Neutron and Archway  starlark and Go packages. The previous approach involved a single large dictionary (args) for passing arguments to functions, which has now been replaced with individual arguments.
```bash
refactor: refactor argument passing in the starlark and go package of neutron and archway
```
```bash
```
> refactor: refactor argument passing in the starlark and go package of neutron and archway

- cli/commands/chain/types/eth.go
- cli/common/constants.go
- main.star
- services/evm/eth/eth.star
- services/evm/eth/src/node-setup/contract-service.star
- services/evm/eth/src/node-setup/start-eth-node.star
- services/evm/eth/src/relay-setup/contract_configuration.star
```bash
refactor: refactor argument passing in eth's starlark and go package
```
```bash
```
> refactor: refactor argument passing in eth's starlark and go package

- main.star
```bash
fix: fix issue while running dive in kurtosis cloud
```
- [x ] I have performed a self-review of my own code
> fix: fix issue while running dive in kurtosis cloud

- README.md
```bash
docs: update dive installation steps for linux
```
> docs: update dive installation steps for linux

- cli/common/types.go
Removed redundant conditions in some parts of the code
```bash
refactor: removed redundant conditions
```
> refactor: removed redundant conditions

- cli/go.mod
```bash
chore: update go mod deps
```
```bash
version: update go mod deps
```
> chore: update go mod deps

- cli/common/constants.go
- cli/go.mod
```bash
chore: bump kurtosis version
```
```bash
version: updated kurtosis version to 0.86.4
```
- [x ] I have performed a self-review of my own code
> chore: bump kurtosis version

- test/scripts/polkadot/package.json
- test/scripts/polkadot/para_relay.js
- test/scripts/polkadot/relay_para.js
```bash
test: e2e script polkadot
```
> test: e2e script polkadot

- test/functional/dive_test.go
- test/functional/go.mod
- test/functional/helper.go
```bash
test: update test script to validate blocks in archway chain
```
> test: update test script to validate blocks in archway chain

- test/functional/dive_test.go
Updated test scripts to validate blocks in neutron chain
```bash
test: updated test scripts to validate blocks in neutron chain
```
> test: updated test scripts to validate blocks in neutron chain
