HugoByte/DIVE

cli/commands/bridge/bridge.go, cli/commands/chain/chains.go, cli/commands/chain/types/eth.go, cli/commands/chain/types/hardhat.go, cli/commands/chain/types/icon.go, cli/commands/discord/discord.go, cli/commands/tutorial/tutorial.go, cli/commands/twitter/twitter.go
```bash
fix: Ckip 85, 86 & 88 
```
=> fix: Ckip 85, 86 & 88 dive discord and help issues

cli/commands/bridge/bridge.go, cli/commands/chain/types/eth.go, cli/commands/chain/types/hardhat.go, cli/commands/chain/types/icon.go, cli/common/types.go
=> fix: file writes

cli/commands/bridge/bridge.go, cli/commands/chain/types/eth.go, cli/commands/chain/types/hardhat.go, cli/commands/chain/types/icon.go, cli/commands/root.go, cli/common/types.go, main.star
```bash
feat: implement bridge logic to handle sequential node run and setup btp 
```
=> feat: implement bridge logic to handle sequential node run and setup btp 

.github/workflows/smoke-test.yaml
```bash
fix: update  gitHub workflow and bump go version to 1.21 to fix gh action issues 
```
```bash
version: update go version 1.21 in github actions  workflow to run smoke test
```
=> fix: gitHub workflow go version issues

cli/.goreleaser.yaml
```bash
feat: update goreleaser.yaml
```
=> feat: update goreleaser.yaml

cli/go.mod
```bash
chore: bump kurtosis sdk version to v0.82.5
```
=> chore: bump kurtosis sdk version to v0.82.5

services/jvm/icon/src/node-setup/setup_icon_node.star, services/jvm/icon/src/relay-setup/contract_configuration.star
Kurtosis is renaming plan.assert to plan.verify so popular Python linters & formatters can be run on .star scripts. We will be shipping a formatter with Kurtosis soon.
This change will work when the following - https://github.com/kurtosis-tech/kurtosis/pull/1295 is merged & released
=> fix: replace plan.assert with plan.verify

cli/go.mod
updated the kurtosis api version in the cli
```bash
chore: bump kurtosis sdk version to v0.83.2
```
```bash
```
=> chore: bump kurtosis sdk version to v0.83.2

services/evm/eth/src/node-setup/start-eth-node.star
kurtosis splitted the parse input function into two section in eth package
```bash
fix: update dive eth package to work with latest eth-network-package 
```
=> fix: update dive eth package to work with latest eth-network-package 

cli/commands/bridge/relays/ibc.go, main.star, services/bridges/ibc/src/bridge.star
```bash
fix: cosmos relay function in bridge
```
=> fix: cosmos relay function in bridge

cli/go.mod
```bash
chore: bump kurtosis sdk to 0.83.6
```
=> chore: bump kurtosis sdk to 0.83.6

cli/commands/bridge/relays/ibc.go, cli/common/constants.go
```bash
fix: error handling in start relay command 
```
```bash
version: bump dive cli version
```
=> fix: error handling in start relay command 

cli/common/constants.go, cli/go.mod
```bash
chore: bump kurtosis sdk version to 0.84.8 and bump dive cli version
```
```bash
version: bump kurtosis sdk version to 0.84.8
```
=> chore: bump kurtosis sdk version to 0.84.8 and bump dive cli version

cli/common/constants.go, cli/go.mod
```bash
chore: kurtosis sdk version bump to v0.85.0
```
```bash
1. Kurtosis SDK version is upgraded from v0.84.8 to v0.85.0 
2. dive-cli version upgraded to v0.0.14-beta
```
=> chore: kurtosis sdk version bump to v0.85.0

README.md, cli/commands/bridge/bridge.go, cli/commands/bridge/relays/btp.go, cli/commands/bridge/relays/common.go, cli/commands/bridge/relays/ibc.go, cli/commands/chain/chains.go, cli/commands/chain/types/archway.go, cli/commands/chain/types/eth.go, cli/commands/chain/types/hardhat.go, cli/commands/chain/types/icon.go, cli/commands/chain/types/neutron.go, cli/commands/clean/clean.go, cli/commands/discord/discord.go, cli/commands/root.go, cli/commands/tutorial/tutorial.go, cli/commands/twitter/twitter.go, cli/commands/version/version.go, cli/go.mod, cli/main.go, test/functional/dive_test.go, test/functional/go.mod
```bash
chore: archiving this repo 
```
```bash
```
=> chore: archiving this repo

cli/cmd/chains/kusama/run.go, cli/cmd/chains/polkadot/run.go, cli/common/context.go, cli/common/interfaces.go
```bash
fix: fix issue invalid explorer url open when run dive on kurtosis cloud
```
```bash
1: Explorer link will not open automatically when running dive on kurtosis cloud
```
=> fix: fix issue invalid explorer url open when run dive on kurtosis cloud

cli/cmd/chains/polkadot/cmd.go, cli/cmd/chains/polkadot/run.go, cli/cmd/chains/utils/types.go
```bash
feat: implement starting collator local node with custom keys
```
```bash
1: user can start polkadot/kusama local parachain collator node with his own keys
```
=> feat: implement starting collator local node with custom keys

test/functional/dive_test.go, test/functional/go.mod, test/functional/helper.go
```bash
chore: update go mod
```
=> chore: update go mod

cli/go.mod
```bash
chore: bump kurtosis version to 0.87.0
```
```bash
version: bump kurtosis version from 0.86.10 to 0.87.0
```
=> chore: bump kurtosis version to 0.87.0

test/functional/dive_test.go
```bash
fix: remove code that deletes config
```
=> fix: remove code that deletes config
